# Generated by Django 4.0.5 on 2022-06-17 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_user_groups_user_is_superuser_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 13, 20, 26, 610514)),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.FileField(default='profile1.png', null=True, upload_to='images/profile/'),
        ),
    ]
